### ISSUE TITLE
wrong dependencies?

### ISSUE THREAD

**Issue by Munter** [unexpectedjs/unexpected-jsdom#2]
magicpen is a depepdency, but is never used in the library itself.

Similarly, magicpen is a devDependency, but only magicpen-prism is beign used in tests

**Comment by papandreou** [comment]
Whoops, `magicpen` was only supposed to be listed under `devDependencies`. Even though it isn't used, it needs to be there to satisfy magicpen-prism's peer dependency. A bit of a wtf.

Fixed in 5.1.0.
